/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_yeoman_photobackup_server_heicToJpeg_HeicToJpeg */

#ifndef _Included_at_yeoman_photobackup_server_heicToJpeg_HeicToJpeg
#define _Included_at_yeoman_photobackup_server_heicToJpeg_HeicToJpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_yeoman_photobackup_server_heicToJpeg_HeicToJpeg
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_yeoman_photobackup_server_heicToJpeg_HeicToJpeg_initialize
  (JNIEnv *, jclass);

/*
 * Class:     at_yeoman_photobackup_server_heicToJpeg_HeicToJpeg
 * Method:    convert
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_at_yeoman_photobackup_server_heicToJpeg_HeicToJpeg_convert
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
