#!/bin/sh
. /etc/rc.subr
name="photobackup"
start_cmd="$photobackup_start"
stop_cmd="$photobackup_stop"
rcvar="photobackup_enable"
pidfile="/var/run/photobackup"

photobackup_start() {
  daemon -u seb -p /var/run/photobackup /home/seb/run-photobackup-server.sh
}

photobackup_stop() {

}

load_rc_config "$name"
run_rc_command "$1"
